### ISSUE TITLE
Truncated blob name

### ISSUE THREAD

**Issue by danielgary** [LanceMcCarthy/Action-AzureBlobUpload#122]
Hey Lance!

Was using this to upload an executable to Azure with the following name: ```./build/bin/data-composer-0.9.7.exe```.  It worked, but the blob name was ```ta-composer-0.9.7.exe```.

Any thoughts on what might have happened?

Here's the configuration I used:
```yaml
      - name: Upload to Azure Blob Storage
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.8.3
        with:
          connection_string: ${{ secrets.AZURE_BLOB_CONNECTION_STRING }}
          container_name: releases
          source_folder: ./build/bin/
```
