### ISSUE TITLE
If no destination_folder specified, it creates one as "no name" and truncates the first character of the filename

### ISSUE THREAD

**Issue by jdenicola-pa** [LanceMcCarthy/Action-AzureBlobUpload#18]
I have a storage container named "testdata" and in my project I have a folder called "TestData" with an Excel File (test.xlsx). I want the test.xlsx file to go in the "root" of the "testdata" container. So I omitted the "destination_folder".

I used this:

```
    - name: Copy test data to blob storage container        
      uses: LanceMcCarthy/Action-AzureBlobUpload@v1.4
      with:
        connection_string: XXX
        container_name: testdata
        source_folder: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/TestAPI/TestData'
        clean_destination_folder: true
        fail_if_source_empty: true  
```

It ended up creating a folder that shows as

`<no name>`

and creates the "test.xlsx" file as "est.xlsx", with the initial "t" missing.

I also tried using:

`destination_folder: /`

but that does the same thing.
