### ISSUE TITLE
retry handling?

### ISSUE THREAD

**Issue by baywet** [LanceMcCarthy/Action-AzureBlobUpload#299]
Hi 👋
I've been experimenting with this extension.
It seems to struggle when lots of files need to be uploaded eventually throwing lots of
```
UnhandledPromiseRejectionWarning: FetchError: request to <redacted> failed, reason: connect ETIMEDOUT 52.239.221.226:443
    at ClientRequest.<anonymous> (/home/runner/work/_actions/LanceMcCarthy/Action-AzureBlobUpload/v2/webpack:/action-azure-upload-blob/node_modules/node-fetch/lib/index.js:1491:1)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1942) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11196)
```

I believe this extension would need some kind of generic retry handling with an exponential backoff to cool down when running hot on the service side.
Additionally, and that part might need to be fixed in the storage client, the client might be establishing one new TCP connection per file upload, which is a recipe to get port exhaustion on the client side.

**Comment by LanceMcCarthy** [comment]
Hi Vincent, Thanks for sharing, I'll review possible approached for retry and backoff logic.

When you say "lots of files" how many are you talking? I need a realistic number and an approximate average file size, so I can test appropriately.

You could also be getting throttled by Azure (I've noticed 4 threads is the maximum before Azure starts treating you as an abuser), but it could also be total file count per session. I need to research both.

**Comment by baywet** [comment]
Thanks for the quick response.
about ~13k files. lots of them being very small [due to a limitation of Blazor Fluent](https://github.com/microsoft/fast-blazor/issues/239)

**Comment by LanceMcCarthy** [comment]
Ah, okay that makes sense. It sounds similar to problems that arise when you need to include a `node_modules` folder in a deployment.

To begin, I'll attempt to replicate the issue by adding such a high-load test to the current workflow https://github.com/LanceMcCarthy/Action-AzureBlobUpload/blob/c718755d45b4bbed42e4fa67909172644be36180/.github/workflows/main_release.yml#L24

I do have some real-world web apps that use this function to publish static web apps. I'll also try to do it with a Blazor project, too.

I will tag this Issue throughout my investigation, so you can be caught up as I learn more.

**Comment by baywet** [comment]
Thanks for the thorough investigation on this. If you're familiar with the dotnet stack you can simply clone https://github.com/microsoft/kiota and run `dotnet publish -c Release` in `src/Kiota.Web`.
Then trying to upload `src\Kiota.Web\bin\Release\net6.0\publish\wwwroot` through this task will repro the issue.

The [whole workflow as an example](https://github.com/microsoft/kiota/blob/a6a7d5d97e3eccc95b1656330e8a57194033e442/.github/workflows/create-release.yml#L56)

**Comment by LanceMcCarthy** [comment]
[I may or may not be familiar with .NET](https://mvp.microsoft.com/en-us/PublicProfile/5000553) ;)

Excellent, that will absolutely speed up my investigation

**Comment by LanceMcCarthy** [comment]
@baywet Can you take a peek at this run https://github.com/LanceMcCarthy/Action-AzureBlobUpload/actions/runs/3371007359/jobs/5592647833

![image](https://user-images.githubusercontent.com/3520532/199284010-2f74b2e8-ce51-4e59-a2b7-75981075ac22.png)


I'm not seeing the problem yet, though I am using a windows runner for this test. Can you give this a quick shot and see if it helps?


```yaml
  publish_kiota_dev:
    name: Publish kiota.dev
    environment:
      name: kiota.dev
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Publish kiota.dev
        run: dotnet publish -c Release
        working-directory: ./src/Kiota.Web

      - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        name: Azure Blob Upload with Destination folder defined
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container_name: $web
          source_folder: src/Kiota.Web/bin/Release/net6.0/publish/wwwroot
          delete_if_exists: true
```
